### ISSUE TITLE
Change test matrix

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#10751]
Our [current framework testing strategy](https://github.com/qooxdoo/qooxdoo/blob/master/.github/workflows/test-framework.yml#L27C1-L31C28) is the following:

```yaml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x, 19.x]
        browser: [chromium]
```

Node v16 and v19 are EOL and should not be supported anymore.

It should instead consist only of actively supported node versions. Also, Firefox should be tested as well.

```yaml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
        browser: [chromium, firefox]
```
