### ISSUE TITLE
regression: properties from included decorators do not get propagated

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9524]
And it seems that the last merged PRs #9518 and/or #9509 introduced a regression:

I have the following decorator definition in my theme:

```javascript
"input-base" : {
  style : {
    radius: 2,
    color : "border-input",
    width: 1,
    innerWidth: 1,
    innerColor: "#f5f5f5"
  }
},

"input" : {
  include: "input-base",
  style : {
    gradientStart : ["#eaeaea", 0],
    gradientEnd : ["#fbfbfb", 100]
  }
},
```

What I suppose to happen is, that the deocorator `input` inherits `width` and `innerWidth` from `input-base`, but it does not happen.

@Adolfrizer and @ronkie could you please check if your PRs broke something? Thank you.

**Comment by level420** [comment]
@Adolfrizer It's definitely https://github.com/qooxdoo/qooxdoo/pull/9518 I've backed out the commit here locally and inheritance works again.

I'm not sure, but this may be due to the shortcut `width: 1` where `width` is defined http://www.qooxdoo.org/devel/api/#qx.ui.decoration.MSingleBorder~setWidth!method_public as being an array, but it also seems to accept the shortcut with a single number `x` which presumably means `[x, x, x, x]`. But this has to be verified.

**Comment by Adolfrizer** [comment]
I've just verified this decorator definition and got the correct result: _the decorator input inherits width and innerWidth from input-base_. I debugged the `resolve` method and took a look at properties by qooxdoo plugin for Chrome - inherited properties exist. 

And my changes (https://github.com/qooxdoo/qooxdoo/pull/9518), as far as I understand, were not related to the shortcut and group properties - I tried to expand them in the previous PR (https://github.com/qooxdoo/qooxdoo/pull/9511) which wasn't merged.

**Comment by level420** [comment]
@Adolfrizer thank you for investigating. It remains the fact that if I revert commit d4d3a359c84cbe9a4262d64dab9a8a57ba4dc953 the decorator above works again with my theme. But maybe the patch unveils a bug in my theme?

I'll let this issue open until I find the time to debug my theme. Let's see if there are other people running into this issue.

BTW: what do you mean with "qooxdoo plugin for Chrome"? Sounds interesting.

**Comment by Adolfrizer** [comment]
@level420 I can attach my test project if needed :)

This plugin
https://chrome.google.com/webstore/detail/qooxdoo-tools/kdobodfpjlfilfoojlmhfikkfmfmnelh?hl=ru

**Comment by level420** [comment]
@Adolfrizer The effect I'm seeing is when a input field gets the focus. Then it seems to jump a bit, because of its different styles attached. When the field gets the focus the decorator changes from `input` to `input-focus` which causes the css class `qx-input` being removed and `qx-input-focus` being added. The class `qx-abstract-field` remains in the class attribute, indifferent which state the input field gets. In the chrome dom inspector I'm getting the following css style definitions for those classes:

```css
.qx-abstract-field {
    display: block;
    position: absolute;
    resize: none;
    border-width: initial;
    border-top-width: initial;
    border-right-width: initial;
    border-bottom-width: initial;
    border-left-width: initial;
    border-style: none;
    border-color: initial;
    border-image: initial;
    padding: 0px;
    margin: 0px;
    background: transparent;
    outline: none;
    border-radius: 0px;
}

.qx-input {
    border-bottom-left-radius: 2px;
    border-bottom-right-radius: 2px;
    border-top-left-radius: 2px;
    border-top-right-radius: 2px;
    box-shadow: rgb(245, 245, 245) 0px 0px 0px 1px inset;
    background: linear-gradient(rgb(234, 234, 234) 0%, rgb(251, 251, 251) 100%) padding-box;
    border-bottom: 1px solid rgb(209, 209, 209);
    border-left: 1px solid rgb(209, 209, 209);
    border-right: 1px solid rgb(209, 209, 209);
    border-top: 1px solid rgb(209, 209, 209);
}

.qx-input-focused {
    box-shadow: rgba(138, 182, 207, 0.8) 0px 0px 2px 1px;
    background: linear-gradient(rgb(234, 234, 234) 0%, rgb(251, 251, 251) 100%) padding-box;
}
```
where `qx-input-focused` is missing the `border-xxx-width` attributes.

Switching over to the `Computed` tab of the dom inspector in chrome shows for unfocused state of the input element a `border-xxx-width` attribute being `1px` while for the focused state it shows `0px` thus causing the jumping effect.

**Comment by level420** [comment]
and here are the  class definitions which are present if d4d3a359c84cbe9a4262d64dab9a8a57ba4dc953 is reverted:
```css
qx-input {
    border-bottom-left-radius: 2px;
    border-bottom-right-radius: 2px;
    border-top-left-radius: 2px;
    border-top-right-radius: 2px;
    box-shadow: rgb(245, 245, 245) 0px 0px 0px 1px inset;
    background: linear-gradient(rgb(234, 234, 234) 0%, rgb(251, 251, 251) 100%) padding-box;
    border-bottom: 1px solid rgb(209, 209, 209);
    border-left: 1px solid rgb(209, 209, 209);
    border-right: 1px solid rgb(209, 209, 209);
    border-top: 1px solid rgb(209, 209, 209);
}

.qx-input-focused {
    border-bottom-left-radius: 2px;
    border-bottom-right-radius: 2px;
    border-top-left-radius: 2px;
    border-top-right-radius: 2px;
    box-shadow: rgb(245, 245, 245) 0px 0px 0px 1px inset, rgba(138, 182, 207, 0.8) 0px 0px 2px 1px;
    background: linear-gradient(rgb(234, 234, 234) 0%, rgb(251, 251, 251) 100%) padding-box;
    border-bottom: 1px solid rgb(209, 209, 209);
    border-left: 1px solid rgb(209, 209, 209);
    border-right: 1px solid rgb(209, 209, 209);
    border-top: 1px solid rgb(209, 209, 209);
}

.qx-abstract-field {
    display: block;
    position: absolute;
    resize: none;
    border-width: initial;
    border-style: none;
    border-color: initial;
    border-image: initial;
    padding: 0px;
    margin: 0px;
    background: transparent;
    outline: none;
    border-radius: 0px;
}
```
as you can see the `qx-input-focus` css class now has `border-xxx` property definitions with `1px` width and the state change from non focused to focused does not cause the jumpt.
